name: "Security Code Scan"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '12 9 * * 4'

jobs:
  SCS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:     
      - uses: actions/checkout@v2

      - name: Set up projects
        uses: security-code-scan/security-code-scan-add-action@main

      - name: Build
        run: |
          dotnet restore
          dotnet build

      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.2
        
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.0'
        
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@main
        
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
